/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Banco;

import ControladorDB.TarjetaDB;
import ControladorDB.TransaccionDB;
import ControladorDB.UsuarioDB;
import Modelo.Banco.Cuenta;
import Modelo.Banco.Tarjeta;
import Modelo.Banco.Transaccion;
import Modelo.Banco.Usuario;
import Utilidades.Utilidades;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class InterfazCajero extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCajero
     */
    public InterfazCajero() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameTipoDeC = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jFrameCantidad = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnRetirar50 = new javax.swing.JButton();
        btnRetirar200 = new javax.swing.JButton();
        btnRetirar500 = new javax.swing.JButton();
        btnRetirar100 = new javax.swing.JButton();
        btnRetirar300 = new javax.swing.JButton();
        btnRetirar1000 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jFrameOpcion = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFrameSaldoActual = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabelSaldoActual = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jFrameUltimosMvts = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUltimosMvts = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jButtonRegresarEnVUCM = new javax.swing.JButton();
        panelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        txtPin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SELECCIONE TIPO DE CUENTA ");

        jButton4.setText("Ahorro");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Monetaria");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(206, 206, 206))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrameTipoDeCLayout = new javax.swing.GroupLayout(jFrameTipoDeC.getContentPane());
        jFrameTipoDeC.getContentPane().setLayout(jFrameTipoDeCLayout);
        jFrameTipoDeCLayout.setHorizontalGroup(
            jFrameTipoDeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameTipoDeCLayout.setVerticalGroup(
            jFrameTipoDeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SELECCIONE CANTIDAD ");

        btnRetirar50.setText("Q.50.00");
        btnRetirar50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar50ActionPerformed(evt);
            }
        });

        btnRetirar200.setText("Q.200.00");
        btnRetirar200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar200ActionPerformed(evt);
            }
        });

        btnRetirar500.setText("Q.500.00");
        btnRetirar500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar500ActionPerformed(evt);
            }
        });

        btnRetirar100.setText("Q.100.00");
        btnRetirar100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar100ActionPerformed(evt);
            }
        });

        btnRetirar300.setText("Q.300.00");
        btnRetirar300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar300ActionPerformed(evt);
            }
        });

        btnRetirar1000.setText("Q.1,000.00");
        btnRetirar1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar1000ActionPerformed(evt);
            }
        });

        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnRetirar500)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRetirar1000))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnRetirar200)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRetirar300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnRetirar50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRetirar100)))
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel5)
                .addGap(0, 144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirar50)
                    .addComponent(btnRetirar100))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirar200)
                    .addComponent(btnRetirar300))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirar500)
                    .addComponent(btnRetirar1000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrameCantidadLayout = new javax.swing.GroupLayout(jFrameCantidad.getContentPane());
        jFrameCantidad.getContentPane().setLayout(jFrameCantidadLayout);
        jFrameCantidadLayout.setHorizontalGroup(
            jFrameCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameCantidadLayout.setVerticalGroup(
            jFrameCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SELECCIONE OPCION");

        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ver Ultimos Movimientos");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ver Saldo Actual");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Retirar Saldo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(225, 225, 225))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrameOpcionLayout = new javax.swing.GroupLayout(jFrameOpcion.getContentPane());
        jFrameOpcion.getContentPane().setLayout(jFrameOpcionLayout);
        jFrameOpcionLayout.setHorizontalGroup(
            jFrameOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameOpcionLayout.setVerticalGroup(
            jFrameOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SALDO ACTUAL");

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelSaldoActual.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Su Saldo es de");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel10)
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabelSaldoActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrameSaldoActualLayout = new javax.swing.GroupLayout(jFrameSaldoActual.getContentPane());
        jFrameSaldoActual.getContentPane().setLayout(jFrameSaldoActualLayout);
        jFrameSaldoActualLayout.setHorizontalGroup(
            jFrameSaldoActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameSaldoActualLayout.setVerticalGroup(
            jFrameSaldoActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jTableUltimosMvts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUltimosMvts);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ULTIMOS CINCO MOVIMIENTOS");

        jButtonRegresarEnVUCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarEnVUCMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel12))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButtonRegresarEnVUCM, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRegresarEnVUCM, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameUltimosMvtsLayout = new javax.swing.GroupLayout(jFrameUltimosMvts.getContentPane());
        jFrameUltimosMvts.getContentPane().setLayout(jFrameUltimosMvtsLayout);
        jFrameUltimosMvtsLayout.setHorizontalGroup(
            jFrameUltimosMvtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameUltimosMvtsLayout.setVerticalGroup(
            jFrameUltimosMvtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameUltimosMvtsLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogin.setBackground(new java.awt.Color(153, 153, 153));
        panelLogin.setToolTipText("");
        panelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("No. Tarjeta");

        jLabel2.setText("PIN");

        txtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaActionPerformed(evt);
            }
        });

        txtPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CAJERO AUTOMATICO");

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCuenta)
                            .addComponent(txtPin, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaActionPerformed

    private void txtPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     //Mostrar ventana de opciones (boton enter de ventana login):
     String numeroTarjeta;
     int pin = Integer.parseInt(txtPin.getText());;
     boolean existeCuenta;
     TarjetaDB tarjetaDB = new TarjetaDB();
     
     numeroTarjeta = txtCuenta.getText();
     
     
        try {
            existeCuenta = tarjetaDB.existeTarjeta(numeroTarjeta);
            
            if(existeCuenta == true){
                if(tarjetaDB.loginCajero(numeroTarjeta, pin) == true){
                    
                    JOptionPane.showMessageDialog(null, "Logeo exitoso");
                    tarjeta = tarjetaDB.selectTarjeta(numeroTarjeta);
                    saldo = tarjeta.getCuenta().getSaldo();
                    System.out.println(saldo);
                    MostrarVentanaTipoCuenta(); 
                }else{
                    JOptionPane.showMessageDialog(null, "Numero de Tarjeta o PIN Incorrecto");
                }
                
                
            }else{
                JOptionPane.showMessageDialog(null, "No existe la tarjeta", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
             
        } catch (SQLException ex) {
            Logger.getLogger(InterfazCajero.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(tarjeta.getCuenta().getId_tipoCuenta() == 2){
            this.setVisible(false);
            MostrarVentanaOpcion();
        }else{
            JOptionPane.showMessageDialog(null, "Tipo cuenta de incorrecto");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // Mostrar ventana de Cantidad a retirar:
        mostrarVentanaCantidad();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // Mostrar ventana de consultar saldo actual:
        botonConsultarSaldoAct();
        double saldo = tarjeta.getCuenta().getSaldo();
        jLabelSaldoActual.setText(String.valueOf(saldo));
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // Regresar a ventana principal:
        BotonRegresarEnVOpcion();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Boton regresar en ventana de Tipo de cuentas:
        BotonRegresarEnVTipoCuenta();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // boton de regresar en ventanaCantidad
        botonRegresarEnVentanaCantidad();
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnRetirar50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar50ActionPerformed
        UsuarioDB usuariodb =  new UsuarioDB();
        Transaccion transaccion = new Transaccion();
        Utilidades utilidad = new Utilidades();
        try {
            if(this.saldo >= 50){
            
                if(usuariodb.retirar(RETIRO_50, tarjeta.getCuenta().getNumeroCuenta()) == true){
                    TransaccionDB transdb= new TransaccionDB();
                    transaccion.setCuenta(tarjeta.getCuenta());
                    transaccion.setMonto(RETIRO_50);
                    transaccion.setFechaTransaccion(utilidad.setDateTime());
                    transaccion.setTipo_trans(RETIRO_CAJERO_AUTOMATICO);
                    transdb.insertTransaccion(transaccion);
                    JOptionPane.showMessageDialog(null, "Retiro exitoso");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo hacer la transaccion");
                }
            
            }else{
                JOptionPane.showMessageDialog(null, "Saldo insuficiente");
            }
        } catch (SQLException ex) {
            Logger.getLogger(InterfazCajero.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnRetirar50ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(tarjeta.getCuenta().getId_tipoCuenta() == 1){
            this.dispose();
            MostrarVentanaOpcion();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnRetirar100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar100ActionPerformed
        // TODO add your handling code here:
         UsuarioDB usuariodb =  new UsuarioDB();
        Transaccion transaccion = new Transaccion();
        Utilidades utilidad = new Utilidades();
        try {
            if(saldo >= 100){
            
                if(usuariodb.retirar(100, tarjeta.getCuenta().getNumeroCuenta()) == true){
                    TransaccionDB transdb= new TransaccionDB();
                    transaccion.setCuenta(tarjeta.getCuenta());
                    transaccion.setMonto(RETIRO_100);
                    transaccion.setFechaTransaccion(utilidad.setDateTime());
                    transaccion.setTipo_trans(RETIRO_CAJERO_AUTOMATICO);
                    transdb.insertTransaccion(transaccion);
                    JOptionPane.showMessageDialog(null, "Retiro exitoso");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo hacer la transaccion");
                }
            
            }else{
                JOptionPane.showMessageDialog(null, "Saldo insuficiente");
            }
        } catch (SQLException ex) {
            Logger.getLogger(InterfazCajero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRetirar100ActionPerformed

    private void btnRetirar200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar200ActionPerformed
        // TODO add your handling code here:
         UsuarioDB usuariodb =  new UsuarioDB();
        Transaccion transaccion = new Transaccion();
        Utilidades utilidad = new Utilidades();
        try {
            if(saldo >= 200){
            
                if(usuariodb.retirar(200, tarjeta.getCuenta().getNumeroCuenta()) == true){
                    TransaccionDB transdb= new TransaccionDB();
                    transaccion.setCuenta(tarjeta.getCuenta());
                    transaccion.setMonto(RETIRO_200);
                    transaccion.setFechaTransaccion(utilidad.setDateTime());
                    transaccion.setTipo_trans(RETIRO_CAJERO_AUTOMATICO);
                    transdb.insertTransaccion(transaccion);
                    JOptionPane.showMessageDialog(null, "Retiro exitoso");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo hacer la transaccion");
                }
            
            }else{
                JOptionPane.showMessageDialog(null, "Saldo insuficiente");
            }
        } catch (SQLException ex) {
            Logger.getLogger(InterfazCajero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRetirar200ActionPerformed

    private void btnRetirar300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar300ActionPerformed
        // TODO add your handling code here:
        UsuarioDB usuariodb =  new UsuarioDB();
        Transaccion transaccion = new Transaccion();
        Utilidades utilidad = new Utilidades();
        try {
            if(saldo >= 300){
            
                if(usuariodb.retirar(300, tarjeta.getCuenta().getNumeroCuenta()) == true){
                    TransaccionDB transdb= new TransaccionDB();
                    transaccion.setCuenta(tarjeta.getCuenta());
                    transaccion.setMonto(RETIRO_300);
                    transaccion.setFechaTransaccion(utilidad.setDateTime());
                    transaccion.setTipo_trans(RETIRO_CAJERO_AUTOMATICO);
                    transdb.insertTransaccion(transaccion);
                    JOptionPane.showMessageDialog(null, "Retiro exitoso");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo hacer la transaccion");
                }
            
            }else{
                JOptionPane.showMessageDialog(null, "Saldo insuficiente");
            }
        } catch (SQLException ex) {
            Logger.getLogger(InterfazCajero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRetirar300ActionPerformed

    private void btnRetirar500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar500ActionPerformed
        // TODO add your handling code here:
         UsuarioDB usuariodb =  new UsuarioDB();
        Transaccion transaccion = new Transaccion();
        Utilidades utilidad = new Utilidades();
        try {
            if(saldo >= 500){
            
                if(usuariodb.retirar(500, tarjeta.getCuenta().getNumeroCuenta()) == true){
                    TransaccionDB transdb= new TransaccionDB();
                    transaccion.setCuenta(tarjeta.getCuenta());
                    transaccion.setMonto(RETIRO_500);
                    transaccion.setFechaTransaccion(utilidad.setDateTime());
                    transaccion.setTipo_trans(RETIRO_CAJERO_AUTOMATICO);
                    transdb.insertTransaccion(transaccion);
                    JOptionPane.showMessageDialog(null, "Retiro exitoso");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo hacer la transaccion");
                }
            
            }else{
                JOptionPane.showMessageDialog(null, "Saldo insuficiente");
            }
        } catch (SQLException ex) {
            Logger.getLogger(InterfazCajero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRetirar500ActionPerformed

    private void btnRetirar1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar1000ActionPerformed
        // TODO add your handling code here:
         UsuarioDB usuariodb =  new UsuarioDB();
        Transaccion transaccion = new Transaccion();
        Utilidades utilidad = new Utilidades();
        try {
            if(saldo >= 1000){
            
                if(usuariodb.retirar(1000, tarjeta.getCuenta().getNumeroCuenta()) == true){
                    TransaccionDB transdb= new TransaccionDB();
                    transaccion.setCuenta(tarjeta.getCuenta());
                    transaccion.setMonto(RETIRO_1000);
                    transaccion.setFechaTransaccion(utilidad.setDateTime());
                    transaccion.setTipo_trans(RETIRO_CAJERO_AUTOMATICO);
                    transdb.insertTransaccion(transaccion);
                    JOptionPane.showMessageDialog(null, "Retiro exitoso");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo hacer la transaccion");
                }
            
            }else{
                JOptionPane.showMessageDialog(null, "Saldo insuficiente");
            }
        } catch (SQLException ex) {
            Logger.getLogger(InterfazCajero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRetirar1000ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //boton para ver ventana de ultimos movimientos
        botonRegresarEnVentVerUltMovt();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Boton de regresar, en ventana Saldo Actual
        botonRegresarEnVentanaSaldoAct();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonRegresarEnVUCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarEnVUCMActionPerformed
        // TODO add your handling code here:
        //boton de regresar en ventana de Ultimos Movimientos
        botonRegresarEnVentVerUltMovt();
    }//GEN-LAST:event_jButtonRegresarEnVUCMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCajero().setVisible(true);
            }
        });
    }

    public void MostrarVentanaOpcion(){
    
        this.jFrameOpcion.setVisible(true);
        this.jFrameOpcion.setSize(600, 500);
        this.jFrameOpcion.setLocationRelativeTo(null);
        this.jFrameTipoDeC.setVisible(false);
        lblNombre.setText(tarjeta.getCuenta().getUser().getNombre()); 
        //usuario y pin de prueba
        /*int noCuentaAcep = 001;
        int noCuenta;
        noCuenta = Integer.parseInt(jTextField1.getText());
        
        int pinCuentaAcep = 1221;
        int pinCuenta;
        pinCuenta = Integer.parseInt(jTextField2.getText());
        
        if(noCuentaAcep == noCuenta && pinCuentaAcep == pinCuenta){
            this.jFrameOpcion.setVisible(true);
            //this.jPanel1.setVisible(false);
            this.jFrameOpcion.setSize(600, 500);
        }
        else{
            System.out.println("Numero de cuenta o pin incorrectos");
        }*/
        
}
         public void MostrarVentanaTipoCuenta(){
         
             this.jFrameTipoDeC.setVisible(true);
             this.jFrameTipoDeC.setSize(600, 500);
             this.jFrameTipoDeC.setLocationRelativeTo(null);
             this.jFrameOpcion.setVisible(false);
     }
         
         public void BotonRegresarEnVOpcion(){
             
             //this.jFrameTipoDeC.setVisible(true);
             //this.jFrameTipoDeC.setSize(600, 500);
             //this.jFrameTipoDeC.setLocationRelativeTo(null);
             this.jFrameOpcion.setVisible(false);
         }
         
         public void BotonRegresarEnVTipoCuenta(){
             
             this.panelLogin.setVisible(true);
             this.jFrameTipoDeC.setVisible(false);
             this.panelLogin.setSize(600, 500);
         }
         
         public void mostrarVentanaCantidad(){ //boton RETIRAR 
             
             this.jFrameCantidad.setVisible(true);
             this.jFrameCantidad.setSize(600, 500);
             this.jFrameCantidad.setLocationRelativeTo(null);
             this.jFrameOpcion.setVisible(false);
         }
         
         public void botonRegresarEnVentanaCantidad(){ //boton de regresar a ventana de opciones
             
             /*this.jFrameOpcion.setVisible(true);
             this.jFrameOpcion.setSize(600, 500);
             this.jFrameOpcion.setLocationRelativeTo(null);*/
             this.jFrameCantidad.setVisible(false);
         }
         
         public void botonRegresarEnVentanaSaldoAct(){
             
             /*this.jFrameOpcion.setVisible(true);
             this.jFrameOpcion.setSize(600, 500);
             this.jFrameOpcion.setLocationRelativeTo(null);*/
             this.jFrameSaldoActual.setVisible(false);
             //this.dispose();
         }
         
         public void botonConsultarSaldoAct(){
             
             this.jFrameSaldoActual.setVisible(true);
             this.jFrameSaldoActual.setSize(600, 500);
             this.jFrameSaldoActual.setLocationRelativeTo(null);
             this.jFrameOpcion.setVisible(false);
         }
         
         public void botonRegresarEnVentVerUltMovt(){
             
             /*this.jFrameOpcion.setVisible(true);
             this.jFrameOpcion.setSize(600, 500);
             this.jFrameOpcion.setLocationRelativeTo(null);*/
             this.jFrameUltimosMvts.setVisible(false);
             //this.dispose();
         }
         
         public void botonVerUltimosMovt(){
             
             this.jFrameUltimosMvts.setVisible(true);
             this.jFrameUltimosMvts.setSize(600, 500);
             this.jFrameUltimosMvts.setLocationRelativeTo(null);
             this.jFrameOpcion.setVisible(false);
         }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetirar100;
    private javax.swing.JButton btnRetirar1000;
    private javax.swing.JButton btnRetirar200;
    private javax.swing.JButton btnRetirar300;
    private javax.swing.JButton btnRetirar50;
    private javax.swing.JButton btnRetirar500;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonRegresarEnVUCM;
    private javax.swing.JFrame jFrameCantidad;
    private javax.swing.JFrame jFrameOpcion;
    private javax.swing.JFrame jFrameSaldoActual;
    private javax.swing.JFrame jFrameTipoDeC;
    private javax.swing.JFrame jFrameUltimosMvts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSaldoActual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUltimosMvts;
    public javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtPin;
    // End of variables declaration//GEN-END:variables
    public Tarjeta tarjeta = null;
    public double saldo = 0;
    public static final double RETIRO_50 = 50;
    public static final double RETIRO_100 = 100;
    public static final double RETIRO_200 = 200;
    public static final double RETIRO_300 = 300;
    public static final double RETIRO_500 = 500;
    public static final double RETIRO_1000 = 1000;
    public static final int RETIRO_CAJERO_AUTOMATICO = 3;
}
