/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Banco;

import ControladorDB.EmpleadoDB;
import Modelo.Banco.Empleado;
import Utilidades.TextPrompt;
import Utilidades.Utilidades;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cr9_g
 */
public class Login extends javax.swing.JFrame implements MouseListener, ActionListener, KeyListener {

    /**
     * Creates new form Login
     */
    public Empleado usuarioLog;
    InicioCaja frmCaja;
    public static AtencionCliente frmAtenCliente;
    public static RecursosHumanos frmRecursosHumanos;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        TextPrompt placeholder1 = new TextPrompt("Ingrese su usuario", txtUsername);
        TextPrompt placeholder2 = new TextPrompt("Ingrese su contraseña", JPassword);

        placeholder1.changeAlpha(70);
        placeholder2.changeAlpha(70);
        placeholder1.changeStyle(Font.BOLD);
        placeholder2.changeStyle(Font.BOLD);

        this.setSize(450, 640);

        btnLogin.addMouseListener(this);
        btnLogin.addActionListener(this);
        JPassword.addKeyListener(this);
    }
    
    public Login(String username){
        initComponents();
        txtUsername.setText(username);
        
        this.setLocationRelativeTo(null);
        TextPrompt placeholder1 = new TextPrompt("Ingrese su usuario", txtUsername);
        TextPrompt placeholder2 = new TextPrompt("Ingrese su contraseña", JPassword);

        placeholder1.changeAlpha(70);
        placeholder2.changeAlpha(70);
        placeholder1.changeStyle(Font.BOLD);
        placeholder2.changeStyle(Font.BOLD);

        this.setSize(450, 640);

        btnLogin.addMouseListener(this);
        btnLogin.addActionListener(this);
        JPassword.addKeyListener(this);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        JPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(410, 610));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(187, 225, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(410, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bank_78392.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 260, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(15, 76, 117));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INICIAR SESION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 380, 50));

        txtUsername.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(107, 107, 107));
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsername.setAlignmentX(0.0F);
        txtUsername.setAlignmentY(0.0F);
        txtUsername.setBorder(null);
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUsername.setSelectionColor(new java.awt.Color(102, 102, 102));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 380, 50));

        JPassword.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        JPassword.setForeground(new java.awt.Color(107, 107, 107));
        JPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JPassword.setAlignmentX(0.0F);
        JPassword.setAlignmentY(0.0F);
        JPassword.setBorder(null);
        jPanel1.add(JPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 380, 50));

        btnLogin.setBackground(new java.awt.Color(50, 130, 184));
        btnLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(235, 247, 253));
        btnLogin.setText("Iniciar Sesión");
        btnLogin.setBorder(null);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setOpaque(true);
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 380, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    private void iniciarSesion() {
        Empleado usuario = new Empleado();
        Utilidades utilidad = new Utilidades();
        usuario.setUsername(txtUsername.getText());
        usuario.setPassword(JPassword.getText());
        usuario.setLast_session(utilidad.setDateTime());
        EmpleadoDB empleadoSQL = new EmpleadoDB();
        Empleado userEmpleado = new Empleado();

        try {
            boolean verificar = empleadoSQL.LoginEmpleado(usuario);
            if (verificar == true) {

                /*frmCaja.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Se Ha logeado correctamente");*/
                //SELECCIONAR TODOS LOS ATRIBUTOS DEL USUARIO EN LA DB
                userEmpleado = empleadoSQL.getEmpleado(usuario);

                int id = userEmpleado.getDepartamento().getId_departamento();
                String usuarioLog = userEmpleado.getUsername();

                switch (id) {
                    case 1:

                        JOptionPane.showMessageDialog(null, "Lo sentimos, pero no puedes ingresar porque ella no te ama! :c ", "Ha ocurrido un errorcito compa", JOptionPane.ERROR_MESSAGE);

                        break;
                    case 2:
                        frmCaja = new InicioCaja(id, usuarioLog, "Cajero", "BancoUMG");
                        JOptionPane.showMessageDialog(null, "¡Bienvenido Nuevamente " + userEmpleado.getNombre()
                                + " " + userEmpleado.getApellido() + "!");
                        this.dispose();
                        frmCaja.setVisible(true);
                        break;

                    case 3:
                        frmAtenCliente = new AtencionCliente();
                        JOptionPane.showMessageDialog(null, "¡Bienvenido Nuevamente " + userEmpleado.getNombre()
                                + " " + userEmpleado.getApellido() + "!");
                        this.setVisible(false);
                        AtencionCliente.labelUser.setText(userEmpleado.getUsername());
                        frmAtenCliente.setLocationRelativeTo(null);
                        frmAtenCliente.setVisible(true);
                        break;

                    case 4:
                        frmRecursosHumanos = new RecursosHumanos();
                        JOptionPane.showMessageDialog(null, "!Bienvenido Nuevamente " + userEmpleado.getNombre()
                                + " " + userEmpleado.getApellido() + "!");
                        this.setVisible(false);
                        frmRecursosHumanos.setLocationRelativeTo(null);
                        frmRecursosHumanos.setVisible(true);
                        break;
                }

            } else if (txtUsername.getText().isEmpty() || JPassword.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Rellene los campos porfavor!");
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectas!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        Object evt = e.getSource();
        
        if(evt.equals(btnLogin)){
            btnLogin.setBackground(new Color(35, 49, 66));
        }
    }

    @Override
    public void mouseExited(MouseEvent e) {
        Object evt = e.getSource();
        
        if(evt.equals(btnLogin)){
            btnLogin.setBackground(new Color(50,130,184));
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Object evt = e.getSource();
        
        if(evt.equals(btnLogin)){
            iniciarSesion();
        }
    }

    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        Object evt = e.getSource();
        
        if(evt.equals(JPassword)){
            if(e.getKeyCode() == KeyEvent.VK_ENTER){
                System.out.println("ha presionado enter");
                iniciarSesion();
            }
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
    }
}
