/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Banco;

import ControladorDB.TransaccionDB;
import ControladorDB.UsuarioDB;
import Modelo.Banco.Cuenta;
import Modelo.Banco.CuentaAhorro;
import Modelo.Banco.CuentaMonetaria;
import Modelo.Banco.Transaccion;
import Utilidades.Utilidades;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mikesb
 */
public class PanelRetirar extends javax.swing.JPanel {

    /**
     * Creates new form panelRetirar
     */
    public PanelRetirar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbltipoCuenta = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblEfectivo = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblDolares = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblNombreCuenta = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtFnumCuenta = new javax.swing.JTextField();
        btnRetirar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 245, 252));
        setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(235, 247, 253));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );

        add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setBackground(new java.awt.Color(235, 247, 253));
        jPanel7.setPreferredSize(new java.awt.Dimension(350, 691));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 7, 118));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(195, 25, 93));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 247, 253));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipo Cuenta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 60));

        lbltipoCuenta.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lbltipoCuenta.setForeground(new java.awt.Color(235, 247, 253));
        lbltipoCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltipoCuenta.setText("Monetaria");
        jPanel1.add(lbltipoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 60));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 220, 190));

        jPanel3.setBackground(new java.awt.Color(249, 89, 89));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(250, 207, 90));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 247, 253));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Efectivo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 60));

        lblEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        lblEfectivo.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblEfectivo.setForeground(new java.awt.Color(235, 247, 253));
        lblEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEfectivo.setText("Q 0.0");
        jPanel3.add(lblEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, 60));

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 220, 190));

        jPanel9.setBackground(new java.awt.Color(242, 35, 109));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(179, 35, 109));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(235, 247, 253));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Dolares");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 60));

        lblDolares.setBackground(new java.awt.Color(255, 255, 255));
        lblDolares.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblDolares.setForeground(new java.awt.Color(235, 247, 253));
        lblDolares.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDolares.setText("$ 0.0");
        jPanel9.add(lblDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 60));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 220, 190));

        add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel8.setBackground(new java.awt.Color(235, 247, 253));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(235, 247, 253));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(15, 76, 117));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Monto");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 620, 50));

        lblNombreCuenta.setFont(new java.awt.Font("Comic Sans MS", 3, 22)); // NOI18N
        lblNombreCuenta.setForeground(new java.awt.Color(69, 93, 122));
        lblNombreCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCuenta.setText("asdasd");
        jPanel5.add(lblNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 620, 50));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 3, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(15, 76, 117));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Número de Cuenta:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 620, 50));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 3, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(15, 76, 117));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Propietario");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 620, 50));

        txtMonto.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(69, 93, 122));
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMonto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(225, 225, 225), new java.awt.Color(255, 255, 255), new java.awt.Color(225, 225, 225)));
        txtMonto.setMargin(new java.awt.Insets(0, 10, 0, 0));
        jPanel5.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 340, 50));

        btnBuscar.setBackground(new java.awt.Color(248, 248, 248));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-icon.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel5.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 50, 50));

        txtFnumCuenta.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFnumCuenta.setForeground(new java.awt.Color(69, 93, 122));
        txtFnumCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFnumCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(225, 225, 225), new java.awt.Color(255, 255, 255), new java.awt.Color(225, 225, 225)));
        txtFnumCuenta.setMargin(new java.awt.Insets(0, 10, 0, 0));
        jPanel5.add(txtFnumCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 340, 50));

        btnRetirar.setBackground(new java.awt.Color(35, 49, 66));
        btnRetirar.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(235, 247, 253));
        btnRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_request_money_32px_1.png"))); // NOI18N
        btnRetirar.setText("  Retirar");
        btnRetirar.setBorder(null);
        btnRetirar.setContentAreaFilled(false);
        btnRetirar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetirar.setOpaque(true);
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        jPanel5.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 350, 50));

        jPanel8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 660, 630));

        jLabel5.setText("               ");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 120, 60, -1));

        add(jPanel8, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setIcon(new ImageIcon(getClass().getResource("/img/search-icon.png")));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setIcon(new ImageIcon(getClass().getResource("/img/search-icon2.png")));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
        UsuarioDB usuarioDB = new UsuarioDB();
        Cuenta cuentica = null;

        try {
            if (usuarioDB.existeCuenta(txtFnumCuenta.getText()) == true) {

                cuentica = usuarioDB.buscarCuenta(txtFnumCuenta.getText());
                this.tipocuenta = cuentica.getId_tipoCuenta();
                btnRetirar.setEnabled(true);
                lblEfectivo.setText("Q " + cuentica.getSaldo());
                DecimalFormat formato = new DecimalFormat("#.00");
                double dolares = (cuentica.getSaldo() / 7.8);
                lblDolares.setText("$ " + (formato.format(dolares)));

                switch (tipocuenta) {
                    case 1:
                    Cuenta cuentaA = new CuentaAhorro();
                    cuentaA = cuentica;
                    lblNombreCuenta.setText(cuentaA.getUser().getNombre() + " " + cuentaA.getUser().getApellido());
                    lbltipoCuenta.setText("Ahorro");
                    break;

                    case 2:
                    Cuenta cuentaM = new CuentaMonetaria();
                    cuentaM = cuentica;
                    lblNombreCuenta.setText(cuentaM.getUser().getNombre() + " " + cuentaM.getUser().getApellido());
                    lbltipoCuenta.setText("Monetaria");
                    break;

                }

            }else{
                JOptionPane.showMessageDialog(null, "La cuenta solicitada no existe", "¡Alerta!", JOptionPane.ERROR_MESSAGE);
                lblNombreCuenta.setText("");
                txtMonto.setText("");
                lbltipoCuenta.setText("");
                btnRetirar.setEnabled(false);
            }

        } catch (SQLException e) {
            e.getMessage();
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
          UsuarioDB usuarioDB = new UsuarioDB();
        Transaccion trans = new Transaccion();
        TransaccionDB transDB = new TransaccionDB();
        Utilidades utilidad = new Utilidades();
        Cuenta cuentica = null;
        String cuenta = txtMonto.getText();

        if (tipocuenta == 1) {
            cuentica = new CuentaAhorro();
        } else if (tipocuenta == 2) {
            cuentica = new CuentaMonetaria();
        }

        if (txtMonto.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null, "El campo está vacío, ingrese una cantidad para continuar", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } else {
            double monto = Double.parseDouble(txtMonto.getText());
            if (monto <= 0) {

                JOptionPane.showMessageDialog(null, "Ingrese una cantidad valida", "¡Error!", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    double saldo = usuarioDB.getSaldo(cuenta);

                    if (monto <= saldo) {

                        cuentica.setNumeroCuenta(cuenta);
                        cuentica.setId_tipoCuenta(tipocuenta);
                        trans.setCuenta(cuentica);
                        trans.setMonto(Double.parseDouble(txtMonto.getText()));
                        trans.setTipo_trans(2);
                        trans.setFechaTransaccion(utilidad.setDateTime());

                        usuarioDB.retirar(monto, cuenta);
                        transDB.insertTransaccion(trans);

                        JOptionPane.showMessageDialog(null, "Retiro realizado con éxito", "Transacción realizada", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "No hay fondos suficientes", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Retirar.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }//GEN-LAST:event_btnRetirarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblDolares;
    private javax.swing.JLabel lblEfectivo;
    private javax.swing.JLabel lblNombreCuenta;
    private javax.swing.JLabel lbltipoCuenta;
    private javax.swing.JTextField txtFnumCuenta;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
    private int tipocuenta;

}
